"""Committed cross-language vectors: every verifier checks the same artifacts.

``verifiers/vectors/v1/*.json`` are generated by
``verifiers/vectors/generate.py`` (re-run on format changes). Each file holds
verbatim journal lines plus expectations both the Python and the Node verifier
must reproduce. Tampered vectors assert identical failure codes.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

from tesera import audit_journal
from tesera.verification import verify_journal

VECTORS_DIR = Path(__file__).resolve().parent.parent / "verifiers" / "vectors" / "v1"
VECTORS = sorted(VECTORS_DIR.glob("*.json"))
VERIFIER = Path(__file__).resolve().parent.parent / "verifiers" / "node" / "verify.mjs"
NODE = shutil.which("node")

needs_node = pytest.mark.skipif(NODE is None, reason="node is not installed")


def _load(vector: Path, tmp_path: Path) -> tuple[Path, list[Ed25519PublicKey], dict]:
    payload = json.loads(vector.read_text())
    journal = tmp_path / f"{vector.stem}.jsonl"
    journal.write_text("\n".join(payload["journal"]) + "\n")
    keys = []
    for pem in payload["public_keys"]:
        key = serialization.load_pem_public_key(pem.encode("ascii"))
        assert isinstance(key, Ed25519PublicKey)
        keys.append(key)
    return journal, keys, payload


@pytest.mark.parametrize("vector", VECTORS, ids=[v.stem for v in VECTORS])
def test_python_reproduces_vector(vector, tmp_path):
    journal, keys, payload = _load(vector, tmp_path)
    expect = payload["expect"]
    result = verify_journal(journal, keys)
    assert result.valid is expect["valid"]
    assert result.events_verified == expect["events_verified"]
    assert sorted({issue.code for issue in result.issues}) == sorted(expect["codes"])
    if "audit" in expect:
        report = audit_journal(journal, keys)
        assert report.structurally_valid is expect["audit"]["structurally_valid"]
        assert sorted(inv.status.value for inv in report.invocations) == sorted(
            expect["audit"]["statuses"]
        )
        assert sorted({issue.code for issue in report.issues}) == sorted(
            expect["audit"]["issue_codes"]
        )


@pytest.mark.parametrize("vector", VECTORS, ids=[v.stem for v in VECTORS])
@needs_node
def test_node_reproduces_vector(vector, tmp_path):
    journal, _, payload = _load(vector, tmp_path)
    key_paths = []
    for index, pem in enumerate(payload["public_keys"]):
        path = tmp_path / f"key-{index}.pem"
        path.write_text(pem)
        key_paths += ["--public-key", str(path)]
    proc = subprocess.run(
        [NODE, str(VERIFIER), "--journal", str(journal), *key_paths, "--json"],
        capture_output=True,
        text=True,
        timeout=60,
    )
    outcome = json.loads(proc.stdout)
    expect = payload["expect"]
    assert outcome["valid"] is expect["valid"]
    assert outcome["events_verified"] == expect["events_verified"]
    assert sorted({issue["code"] for issue in outcome["issues"]}) == sorted(expect["codes"])
